#!/usr/bin/env python3
import argparse
import json
import pathlib
import sys

from validate_repo_contracts import collect_instance_validation_errors


FIXTURE_ROOT = pathlib.Path("tests") / "typescript_importer" / "cases"
SUPPORTED_MODES = ("validate-fixtures", "test")
PLACEHOLDER_VALIDATOR = "typescript-phase7-placeholder-bundle"
SHARED_PROFILES = ["R", "D-JS"]
ADMITTED_SUMMARY = {"A": 1, "B": 0, "C": 0, "D": 0}
REJECTED_SUMMARY = {"A": 0, "B": 0, "C": 0, "D": 1}
COMMON_JSON_ARTIFACTS = {
    "module_manifest.json": "schemas/module_manifest.schema.json",
    "feature_tier_report.json": "schemas/feature_tier_report.schema.json",
    "validation_report.json": "schemas/validation_report.schema.json",
}

CASE_EXPECTATIONS = {
    "a_interface_decl": {
        "tier": "A",
        "status": "warn",
        "summary": ADMITTED_SUMMARY,
        "require_scirh": True,
        "diagnostic_severity": "warn",
        "source_markers": [
            "fixture.typescript_importer.a_interface_decl",
            "Reserved Phase 7 admitted TypeScript bundle.",
            "not a live fixture input.",
        ],
        "scirh_markers": [
            "RESERVED_PLACEHOLDER_NONCANONICAL_SCIRH",
            "case_id: a_interface_decl",
            "status: not generated by a live TypeScript importer or validator",
        ],
        "feature_markers": [
            "reserved interface-declaration placeholder bundle",
            "reserved placeholder evidence",
            "not a live importer result",
        ],
        "diagnostic_markers": [
            "no live TypeScript importer",
        ],
    },
    "a_interface_local_witness_use": {
        "tier": "A",
        "status": "warn",
        "summary": ADMITTED_SUMMARY,
        "require_scirh": True,
        "diagnostic_severity": "warn",
        "source_markers": [
            "fixture.typescript_importer.a_interface_local_witness_use",
            "Reserved Phase 7 admitted TypeScript bundle.",
            "not a live fixture input.",
        ],
        "scirh_markers": [
            "RESERVED_PLACEHOLDER_NONCANONICAL_SCIRH",
            "case_id: a_interface_local_witness_use",
            "status: not generated by a live TypeScript importer or validator",
        ],
        "feature_markers": [
            "reserved module-local witness-use placeholder bundle",
            "reserved placeholder evidence",
            "not a live importer result",
        ],
        "diagnostic_markers": [
            "no live TypeScript importer",
        ],
    },
    "d_function_decl": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_function_decl",
            "Reserved Phase 7 rejected boundary placeholder for function declarations.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "function declaration",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_async_function": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_async_function",
            "Reserved Phase 7 rejected boundary placeholder for async function declarations.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "async function declaration",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_class_implements_interface": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_class_implements_interface",
            "Reserved Phase 7 rejected boundary placeholder for class plus interface implementation shapes.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "class implementing interface",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_prototype_assignment": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_prototype_assignment",
            "Reserved Phase 7 rejected boundary placeholder for prototype assignments.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "prototype assignment",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_decorator_class": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_decorator_class",
            "Reserved Phase 7 rejected boundary placeholder for decorator-bearing classes.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "decorator-bearing class",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_proxy_construct": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_proxy_construct",
            "Reserved Phase 7 rejected boundary placeholder for proxy construction.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "proxy construction",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
    "d_type_level_runtime_gate": {
        "tier": "D",
        "status": "fail",
        "summary": REJECTED_SUMMARY,
        "require_scirh": False,
        "diagnostic_severity": "error",
        "feature_fallback": "reject",
        "source_markers": [
            "fixture.typescript_importer.d_type_level_runtime_gate",
            "Reserved Phase 7 rejected boundary placeholder for executable type-level runtime gates.",
            "not a live fixture input.",
        ],
        "feature_markers": [
            "executable type-level runtime gate",
            "reserved placeholder evidence only",
            "does not record a live importer rejection",
        ],
        "diagnostic_markers": [
            "canonical SCIR-H is intentionally absent",
            "no live TypeScript importer",
        ],
    },
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "TypeScript importer conformance checker for the dormant Phase 7 "
            "interface-witness placeholder corpus."
        )
    )
    parser.add_argument(
        "--mode",
        choices=SUPPORTED_MODES,
        default="validate-fixtures",
        help=(
            "`validate-fixtures` checks dormant corpus integrity. "
            "`test` remains reserved for future generated-vs-golden conformance."
        ),
    )
    return parser


def load_json(path: pathlib.Path):
    return json.loads(path.read_text(encoding="utf-8"))


def load_schema(root: pathlib.Path, relative_path: str):
    return load_json(root / relative_path)


def validate_json_against_schema(root: pathlib.Path, json_path: pathlib.Path, schema_rel: str):
    schema = load_schema(root, schema_rel)
    instance = load_json(json_path)
    failures = []
    for location, message in collect_instance_validation_errors(instance, schema):
        failures.append(f"{json_path.relative_to(root)} {location}: {message}")
    return instance, failures


def summarize_item_tiers(items):
    summary = {"A": 0, "B": 0, "C": 0, "D": 0}
    for item in items:
        tier = item.get("tier")
        if tier in summary:
            summary[tier] += 1
    return summary


def expected_file_set(expectation: dict):
    files = {
        "README.md",
        "source.ts",
        "module_manifest.json",
        "feature_tier_report.json",
        "validation_report.json",
    }
    if expectation["require_scirh"]:
        files.add("expected.scirh")
    return files


def check_markers(text: str, markers: list[str], *, label: str, failures: list[str]):
    for marker in markers:
        if marker not in text:
            failures.append(f"{label}: missing marker {marker!r}")


def check_case(root: pathlib.Path, case_name: str, expectation: dict):
    failures = []
    case_dir = root / FIXTURE_ROOT / case_name
    if not case_dir.exists():
        return [f"missing fixture case directory: {case_dir.relative_to(root)}"]

    expected_names = expected_file_set(expectation)
    actual_names = {path.name for path in case_dir.iterdir()}
    for name in sorted(expected_names - actual_names):
        failures.append(f"{case_dir.relative_to(root)}: missing required file {name}")
    for name in sorted(actual_names - expected_names):
        failures.append(f"{case_dir.relative_to(root)}: unexpected file-system entry {name}")

    source_path = case_dir / "source.ts"
    if source_path.exists():
        source_text = source_path.read_text(encoding="utf-8")
        check_markers(
            source_text,
            expectation["source_markers"],
            label=str(source_path.relative_to(root)),
            failures=failures,
        )

    scirh_path = case_dir / "expected.scirh"
    if expectation["require_scirh"]:
        if scirh_path.exists():
            scirh_text = scirh_path.read_text(encoding="utf-8")
            check_markers(
                scirh_text,
                expectation["scirh_markers"],
                label=str(scirh_path.relative_to(root)),
                failures=failures,
            )
            if scirh_text.lstrip().startswith("module "):
                failures.append(
                    f"{scirh_path.relative_to(root)}: expected non-canonical placeholder sentinel, not canonical SCIR-H"
                )
    elif scirh_path.exists():
        failures.append(
            f"{scirh_path.relative_to(root)}: rejected placeholder cases must not include expected.scirh"
        )

    manifest_instance = None
    feature_instance = None
    validation_instance = None
    for artifact_name, schema_rel in COMMON_JSON_ARTIFACTS.items():
        artifact_path = case_dir / artifact_name
        if artifact_path.exists():
            instance, artifact_failures = validate_json_against_schema(root, artifact_path, schema_rel)
            failures.extend(artifact_failures)
            if artifact_name == "module_manifest.json":
                manifest_instance = instance
            elif artifact_name == "feature_tier_report.json":
                feature_instance = instance
            else:
                validation_instance = instance

    expected_module_id = f"fixture.typescript_importer.{case_name}"
    expected_source_path = (FIXTURE_ROOT / case_name / "source.ts").as_posix()
    kebab_case_name = case_name.replace("_", "-")

    if manifest_instance is not None:
        manifest_path = case_dir / "module_manifest.json"
        if manifest_instance.get("module_id") != expected_module_id:
            failures.append(f"{manifest_path.relative_to(root)}: expected module_id {expected_module_id!r}")
        if manifest_instance.get("layer") != "scir_h":
            failures.append(f"{manifest_path.relative_to(root)}: expected layer 'scir_h'")
        if manifest_instance.get("source_language") != "typescript":
            failures.append(f"{manifest_path.relative_to(root)}: expected source_language 'typescript'")
        if manifest_instance.get("source_path") != expected_source_path:
            failures.append(f"{manifest_path.relative_to(root)}: expected source_path {expected_source_path!r}")
        if manifest_instance.get("declared_profiles") != SHARED_PROFILES:
            failures.append(f"{manifest_path.relative_to(root)}: expected declared_profiles {SHARED_PROFILES!r}")
        if manifest_instance.get("declared_tier") != expectation["tier"]:
            failures.append(
                f"{manifest_path.relative_to(root)}: expected declared_tier {expectation['tier']!r}"
            )
        if manifest_instance.get("dependencies") != []:
            failures.append(f"{manifest_path.relative_to(root)}: expected dependencies []")

    if feature_instance is not None:
        feature_path = case_dir / "feature_tier_report.json"
        if feature_instance.get("report_id") != f"fixture-feature-tier-{kebab_case_name}":
            failures.append(
                f"{feature_path.relative_to(root)}: expected report_id 'fixture-feature-tier-{kebab_case_name}'"
            )
        if feature_instance.get("subject") != expected_module_id:
            failures.append(f"{feature_path.relative_to(root)}: expected subject {expected_module_id!r}")
        if feature_instance.get("source_language") != "typescript":
            failures.append(f"{feature_path.relative_to(root)}: expected source_language 'typescript'")
        if feature_instance.get("summary") != expectation["summary"]:
            failures.append(f"{feature_path.relative_to(root)}: expected summary {expectation['summary']!r}")
        items = feature_instance.get("items", [])
        if len(items) != 1:
            failures.append(f"{feature_path.relative_to(root)}: expected exactly one tier item")
        else:
            item = items[0]
            if item.get("tier") != expectation["tier"]:
                failures.append(
                    f"{feature_path.relative_to(root)}: expected item tier {expectation['tier']!r}"
                )
            feature_text = "\n".join(
                str(item.get(field, ""))
                for field in ("feature", "rationale", "fallback")
                if field in item
            )
            check_markers(
                feature_text,
                expectation["feature_markers"],
                label=str(feature_path.relative_to(root)),
                failures=failures,
            )
            expected_fallback = expectation.get("feature_fallback")
            if expected_fallback is None:
                if "fallback" in item:
                    failures.append(f"{feature_path.relative_to(root)}: admitted cases must not set fallback")
            elif item.get("fallback") != expected_fallback:
                failures.append(
                    f"{feature_path.relative_to(root)}: expected fallback {expected_fallback!r}"
                )
        derived_summary = summarize_item_tiers(items)
        if derived_summary != feature_instance.get("summary"):
            failures.append(
                f"{feature_path.relative_to(root)}: summary does not match the tiers present in items"
            )

    if validation_instance is not None:
        validation_path = case_dir / "validation_report.json"
        if validation_instance.get("report_id") != f"fixture-validation-{kebab_case_name}":
            failures.append(
                f"{validation_path.relative_to(root)}: expected report_id 'fixture-validation-{kebab_case_name}'"
            )
        if validation_instance.get("artifact") != expected_module_id:
            failures.append(f"{validation_path.relative_to(root)}: expected artifact {expected_module_id!r}")
        if validation_instance.get("layer") != "scir_h":
            failures.append(f"{validation_path.relative_to(root)}: expected layer 'scir_h'")
        if validation_instance.get("validator") != PLACEHOLDER_VALIDATOR:
            failures.append(
                f"{validation_path.relative_to(root)}: expected validator {PLACEHOLDER_VALIDATOR!r}"
            )
        if validation_instance.get("spec_version") != "v0.1-draft":
            failures.append(f"{validation_path.relative_to(root)}: expected spec_version 'v0.1-draft'")
        if validation_instance.get("status") != expectation["status"]:
            failures.append(
                f"{validation_path.relative_to(root)}: expected status {expectation['status']!r}"
            )
        diagnostics = validation_instance.get("diagnostics", [])
        if len(diagnostics) != 1:
            failures.append(f"{validation_path.relative_to(root)}: expected exactly one diagnostic")
        else:
            diagnostic = diagnostics[0]
            if diagnostic.get("severity") != expectation["diagnostic_severity"]:
                failures.append(
                    f"{validation_path.relative_to(root)}: expected diagnostic severity {expectation['diagnostic_severity']!r}"
                )
            if diagnostic.get("location") != "source.ts:1":
                failures.append(f"{validation_path.relative_to(root)}: expected diagnostic location 'source.ts:1'")
            diagnostic_message = str(diagnostic.get("message", ""))
            diagnostic_message_lower = diagnostic_message.lower()
            for marker in expectation["diagnostic_markers"]:
                if marker.lower() not in diagnostic_message_lower:
                    failures.append(
                        f"{validation_path.relative_to(root)}: expected diagnostic message to mention {marker!r}"
                    )

    return failures


def validate_fixtures(root: pathlib.Path):
    failures = []
    fixture_root = root / FIXTURE_ROOT
    if not fixture_root.exists():
        return [f"missing fixture root: {fixture_root.relative_to(root)}"]

    expected_cases = set(CASE_EXPECTATIONS)
    actual_cases = {path.name for path in fixture_root.iterdir() if path.is_dir()}
    for case_name in sorted(expected_cases - actual_cases):
        failures.append(f"{FIXTURE_ROOT.as_posix()}: missing fixture case {case_name}")
    for case_name in sorted(actual_cases - expected_cases):
        failures.append(f"{FIXTURE_ROOT.as_posix()}: unexpected fixture case {case_name}")
    for case_name in sorted(expected_cases & actual_cases):
        failures.extend(check_case(root, case_name, CASE_EXPECTATIONS[case_name]))
    return failures


def print_success():
    print("[validate-fixtures] TypeScript importer conformance passed")
    print(
        "Checked exact case matrix, placeholder source markers, admitted sentinel "
        "expected.scirh files, schema-valid report artifacts, admitted-vs-rejected "
        f"file rules, and placeholder diagnostic posture for {len(CASE_EXPECTATIONS)} "
        "TypeScript importer cases."
    )


def print_reserved_test_message():
    print(
        "[reserved] TypeScript importer generated-vs-golden conformance is not implemented.\n"
        " - requested mode: test\n"
        f" - reserved corpus root: {FIXTURE_ROOT.as_posix()}\n"
        " - validate-fixtures status: active for the dormant placeholder corpus\n"
        " - no live TypeScript importer, generated-vs-golden conformance, SCIR-L, "
        "reconstruction, benchmark, or executable D-JS path exists yet",
        file=sys.stderr,
    )


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if args.mode == "test":
        print_reserved_test_message()
        return 2

    root = pathlib.Path(__file__).resolve().parents[1]
    failures = validate_fixtures(root)
    if failures:
        print("[validate-fixtures] TypeScript importer conformance failed")
        for item in failures:
            print(f" - {item}")
        return 1

    print_success()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
